import 'package:flutter/material.dart';
import 'package:qr_scanner_practice/core/app_theming/app_color_theme_extension.dart';

class AppDarkThemeColors extends AppColorThemeExtension {
  AppDarkThemeColors({
    super.primaryDefault = const Color(0xFF2096F3),
    super.primaryPressed = const Color(0xFF1976D2),
    super.primaryDisabled = const Color(0xFF374151),
    super.secondaryDefaultTextBorder = const Color(0xFF2096F3),
    super.secondaryPressedTextBorder = const Color(0xFF1976D2),
    super.secondaryPressedBackground = const Color(0xFF1F2937),
    super.secondaryDisabledTextBorder = const Color(0xFF4B5563),
    super.accentDefault = const Color(0xFF2096F3),
    super.accentPressed = const Color(0xFF1976D2),
    super.semanticsTextSuccess = const Color(0xFF4CAF50),
    super.semanticsIconSuccess = const Color(0xFF4CAF50),
    super.semanticsTextError = const Color(0xFFEF5350),
    super.semanticsIconError = const Color(0xFFEF5350),
    super.textPrimary = const Color(0xFFF9FAFB),
    super.textSecondary = const Color(0xFF9CA3AF),
    super.textTertiary = const Color(0xFF6B7280),
    super.textDisabled = const Color(0xFF4B5563),
    super.textInversePrimary = const Color(0xFF111827),
    super.textInverseSecondary = const Color(0xFF374151),
    super.surfaceL1 = const Color(0xFF111827),
    super.surfaceL2 = const Color(0xFF1F2937),
    super.surfaceL3 = const Color(0xFF374151),
    super.separator = const Color(0xFF374151),
    super.borderInputDefault = const Color(0xFF4B5563),
    super.borderInputFocused = const Color(0xFF2096F3),
    super.iconPrimary = const Color(0xFFF9FAFB),
    super.iconSecondary = const Color(0xFF9CA3AF),
    super.iconTertiary = const Color(0xFF6B7280),
    super.scanFrameCorner = const Color(0xFF2096F3),
    super.scanLineGradient = const Color(0xFF2096F3),
    super.cameraOverlay = const Color(0x80000000),
    super.flashActive = const Color(0xFF2096F3),
    super.sheetCardSelected = const Color(0xFF2096F3),
    super.qrBadgeBackground = const Color(0x1A2196F3),
    super.qrBadgeText = const Color(0xFF60A5FA),
    super.ocrBadgeBackground = const Color(0x1A9C27B0),
    super.ocrBadgeText = const Color(0xFFBA68C8),
    super.scaffoldBackground = const Color(0xFF111827),
    super.appBarBackground = const Color(0xFF1F2937),
    super.buttonPrimaryBackground = const Color(0xFF2096F3),
    super.buttonSecondaryBackground = const Color(0xFF1F2937),
    super.bottomNavBackground = const Color(0xFF1F2937),
    super.cardBackground = const Color(0xFF1F2937),
    super.dialogBackground = const Color(0xFF1F2937),
    super.snackbarBackground = const Color(0xFF374151),
    super.splashBackground = const Color(0xFF2096F3),
    super.splashLogoTint = const Color(0xFF2096F3),
    super.splashText = const Color(0xFFF9FAFB),
    super.splashIndicator = const Color(0xFF2096F3),
    super.switchActiveTrack = const Color(0xFF2096F3),
    super.switchActiveThumb = const Color(0xFFF9FAFB),
    super.switchInactiveTrack = const Color(0xFF4B5563),
    super.switchInactiveThumb = const Color(0xFFF9FAFB),
  });
}
